### ISSUE TITLE
Question Regarding Visualization Rendering

### ISSUE THREAD

**Issue by paxtaeo** [autonomousvision/king#3]
Hello, I'm very grateful for your neatly organized code; it has been immensely helpful in discussing follow-up research. I've been trying to visualize scenarios, and I have a question in this process.

I tried rendering using tools/visualize_scenarios.py, but only very condensed images come out unlike your example images. I looked into the code a bit and tried using CARLARenderer instead of BaseRenderer, but the result was the same.
![RouteScenario_124_iter_13](https://github.com/autonomousvision/king/assets/82695409/9a8f42cb-3df3-4e7e-bec8-15a0cb7935c6)

Could you tell me how you proceeded with the visualization?

**Comment by lasnik** [comment]
Hi @paxtaeo! As mentioned in #1 , this is the visualization we used during development for this project and found to be sufficient for that purpose. If you want to generate figures like those in the paper, you're correct in looking at `CARLARenderer` for that. You should be able to get similar results by:

1. Using the spectator camera sensor to get BEV images
2. Placing it at a reasonable static location in the scene (we adjusted this manually, since we only rendered this fancier visualization for a few interesting scenarios)
3. Using CARLA's debug drawing API to draw the trajectory trails directly in the simulator
4. Adapting tools/visualize_scenarios.py to export these images instead of the semantic BEV grid.

Hope this helps!
